<p>1. Ajude João a criar um código que carregue o arquivo JSON como um DataFrame.</p>

In [1]:
import pandas as pd

In [2]:
df = pd.read_json('arquivos/questao_1.json')
df

,id_pedido,id_cliente,nome_cliente,id_produto,nome_produto,categoria,quantidade,preco_unitario,preco_total,data_pedido,status
0,1,101,Alice Silva,201,Camiseta Básica,Roupas,2,50,100,2025-01-01,Entregue
1,2,102,Bruno Souza,202,Tênis Esportivo,Calçados,1,200,200,2025-01-02,Pendente
2,3,103,Carla Pereira,203,Relógio Digital,Acessórios,1,150,150,2025-01-03,Entregue
3,4,104,Daniel Oliveira,204,Calça Jeans,Roupas,2,120,240,2025-01-04,Cancelado
4,15,115,Olivia Rocha,215,Tênis Casual,Calçados,1,220,220,2025-01-15,Entregue

<p>2. Márcia deseja saber a forma mais eficiente de carregar esses dados no Python para manipulá-los como DataFrames. Analise os conjuntos e indique a melhor abordagem para resolver o problema.</p>

In [3]:
df_1 = pd.read_json('arquivos/questao_2_1.json')
df_1

,id_pedido,id_cliente,nome_cliente,id_produto,nome_produto,categorias,quantidade,preco_unitario,preco_total,data_pedido,status
0,10,110,João Vieira,210,Smartphone,"[Eletrônicos, Comunicação, Tecnologia]",1,2500,2500,2025-01-10,Pendente
1,11,111,Karen Martins,211,Mouse Gamer,"[Eletrônicos, Acessórios, Games]",1,150,150,2025-01-11,Entregue
2,12,112,Lucas Mendes,212,Bicicleta,"[Esportes, Lazer, Transporte]",1,1200,1200,2025-01-12,Cancelado
3,13,113,Mariana Lopes,213,Óculos de Sol,"[Acessórios, Moda, Proteção]",1,300,300,2025-01-13,Entregue
4,14,114,Natan Santos,214,Tablet,"[Eletrônicos, Tecnologia, Educação]",1,1500,1500,2025-01-14,Pendente

In [4]:
df_2 = pd.read_json('arquivos/questao_2_2.json')
df_2

,id_pedido,id_cliente,nome_cliente,id_produto,nome_produto,categoria,quantidade,preco_unitario,preco_total,data_pedido,status,endereco
0,5,105,Eduarda Costa,205,Mochila Escolar,Acessórios,1,180,180,2025-01-05,Entregue,"{Rua das Flores, 120, Centro, São Paulo, SP, 0..."
1,6,106,Fernando Lima,206,Notebook,Eletrônicos,1,3000,3000,2025-01-06,Pendente,"{Avenida Paulista, 1578, Bela Vista, São Paulo..."
2,7,107,Gabriela Souza,207,Fone de Ouvido,Eletrônicos,1,250,250,2025-01-07,Entregue,"{Rua do Comércio, 45, Centro, Rio de Janeiro, ..."
3,8,108,Hugo Almeida,208,Jaqueta de Couro,Roupas,1,350,350,2025-01-08,Entregue,"{Rua das Palmeiras, 234, Botafogo, Rio de Jane..."
4,9,109,Isabela Nunes,209,Caderno Universitário,Papelaria,5,20,100,2025-01-09,Entregue,"{Rua da Paz, 789, Centro, Curitiba, PR, 80010-..."

<p>3. Thais utilizou a função pd.read_json para carregar um arquivo JSON recebido em sua empresa. No entanto, ela notou que não conseguia acessar corretamente todos os dados do arquivo no DataFrame.

Um problema identificado foi que a coluna detalhes_compra apresentava informações importantes em formato de dicionário, dificultando a manipulação dos dados:</p>

In [5]:
import json
import pandas as pd

with open('arquivos/questao_3.json', 'r') as f:
    df_3 = json.load(f)

In [6]:
df_3 = pd.json_normalize(df_3)

In [7]:
df_3

,id_pedido,id_cliente,nome_cliente,data_pedido,status,detalhes_compra.id_produto,detalhes_compra.nome_produto,detalhes_compra.categoria,detalhes_compra.quantidade,detalhes_compra.preco_unitario,detalhes_compra.preco_total
0,16,116,Paulo Barros,2025-01-16,Pendente,216,CÃ¢mera Digital,EletrÃ´nicos,1,2000.0,2000.0
1,17,117,Quezia Fernandes,2025-01-17,Entregue,217,Bolsa de Couro,AcessÃ³rios,1,400.0,400.0
2,18,118,Rafael Cardoso,2025-01-18,Cancelado,218,Livro de FicÃ§Ã£o,Livros,2,35.0,70.0
3,19,119,Sofia Ribeiro,2025-01-19,Entregue,219,Perfume,Beleza,1,180.0,180.0
4,20,120,Tiago Moraes,2025-01-20,Entregue,220,Guarda-Chuva,AcessÃ³rios,1,50.0,50.0

<p>4. Como Fábio nunca trabalhou com a normalização de arquivos JSON, ele não sabe como lidar com um arquivo aninhado dessa complexidade. O que Fábio pode fazer para transformar esse JSON em um conjunto de dados utilizável?</p>

In [8]:
with open('arquivos/questao_4.json', 'r') as f:
    df_4 = json.load(f)

In [9]:
df_4 = pd.json_normalize(df_4)

In [10]:
df_4

,id_pedido,data_pedido,status,cliente.id_cliente,cliente.nome_cliente,detalhes_compra.produto.id_produto,detalhes_compra.produto.nome_produto,detalhes_compra.produto.categoria,detalhes_compra.quantidade,detalhes_compra.preco_unitario,detalhes_compra.preco_total
0,21,2025-01-21,Entregue,121,Ursula Castro,221,SandÃ¡lia Feminina,CalÃ§ados,1,90.0,90.0
1,22,2025-01-22,Pendente,122,Victor Andrade,222,Chuteira,Esportes,1,230.0,230.0
2,23,2025-01-23,Entregue,123,Wagner Neves,223,Carregador PortÃ¡til,EletrÃ´nicos,1,100.0,100.0
3,24,2025-01-24,Entregue,124,Xavier Almeida,224,Bola de Futebol,Esportes,1,120.0,120.0
4,25,2025-01-25,Cancelado,125,Yasmin Dias,225,Maquiagem Completa,Beleza,1,250.0,250.0

<p>5. Tiago gostaria de usar o caractere '_' como separador, resultando em nomes de colunas como cliente_id_cliente, cliente_nome_cliente, compra_id_produto e compra_nome_produto. Como Tiago pode alterar o separador de colunas para '_' ao realizar a normalização?</p>

In [11]:
with open('arquivos/questao_5.json', 'r', encoding='utf-8') as f:
    df_5 = json.load(f)

In [12]:
df_5 = pd.json_normalize(df_5, sep='_')

<p>6. Ajude Cristina a criar um DataFrame que permita a manipulação adequada de todos os dados.</p>

In [13]:
with open('arquivos/questao_6.json', 'r', encoding='utf-8') as f:
    df_6 = json.load(f)

In [14]:
df_6 = pd.json_normalize(df_6, record_path='lista_lojas')

<p>7. Juan recebeu um conjunto de dados em formato JSON e precisa normalizá-lo para acessar as informações de maneira estruturada. No entanto, ao utilizar json_normalize, ele identificou que o arquivo continha duas listas

Como Juan pode estruturar esses dados em um único DataFrame?</p>

In [15]:
with open('arquivos/questao_7.json', 'r', encoding='utf-8') as f:
    df_7 = json.load(f)

In [16]:
df_7

{'lojas_sudeste': [{'id_loja': 1,
   'nome_loja': 'Loja Alpha',
   'cidade': 'São Paulo',
   'estado': 'SP',
   'categoria': 'Eletrônicos',
   'vendas_mensais': 150,
   'faturamento_mensal': 45000.0},
  {'id_loja': 2,
   'nome_loja': 'Loja Beta',
   'cidade': 'Rio de Janeiro',
   'estado': 'RJ',
   'categoria': 'Roupas',
   'vendas_mensais': 200,
   'faturamento_mensal': 60000.0}],
 'lojas_sul': [{'id_loja': 3,
   'nome_loja': 'Loja Gamma',
   'cidade': 'Belo Horizonte',
   'estado': 'MG',
   'categoria': 'Calçados',
   'vendas_mensais': 120,
   'faturamento_mensal': 36000.0},
  {'id_loja': 4,
   'nome_loja': 'Loja Delta',
   'cidade': 'Curitiba',
   'estado': 'PR',
   'categoria': 'Acessórios',
   'vendas_mensais': 80,
   'faturamento_mensal': 24000.0}]}

In [17]:
lojas_sudeste = pd.json_normalize(df_7, record_path='lojas_sudeste',)
lojas_sul = pd.json_normalize(df_7, record_path='lojas_sul')

In [18]:
todas_lojas = pd.merge(lojas_sudeste, lojas_sul, 'outer', indicator=True)

In [19]:
todas_lojas.reset_index(drop=True, inplace=True)

In [20]:
todas_lojas

,id_loja,nome_loja,cidade,estado,categoria,vendas_mensais,faturamento_mensal,_merge
0,1,Loja Alpha,São Paulo,SP,Eletrônicos,150,45000.0,left_only
1,2,Loja Beta,Rio de Janeiro,RJ,Roupas,200,60000.0,left_only
2,3,Loja Gamma,Belo Horizonte,MG,Calçados,120,36000.0,right_only
3,4,Loja Delta,Curitiba,PR,Acessórios,80,24000.0,right_only

<p>Segunda alternativa</p>

In [21]:
df_final = pd.concat([lojas_sudeste, lojas_sul], ignore_index=True)
df_final

,id_loja,nome_loja,cidade,estado,categoria,vendas_mensais,faturamento_mensal
0,1,Loja Alpha,São Paulo,SP,Eletrônicos,150,45000.0
1,2,Loja Beta,Rio de Janeiro,RJ,Roupas,200,60000.0
2,3,Loja Gamma,Belo Horizonte,MG,Calçados,120,36000.0
3,4,Loja Delta,Curitiba,PR,Acessórios,80,24000.0

<p>8. Paula está trabalhando com um conjunto de dados que contém duas listas aninhadas dentro de uma chave chamada lojas. Devido a essa estrutura, ela está enfrentando dificuldades para transformar o documento em um DataFrame manipulável.</p>

In [22]:
pd.read_json('arquivos/questao_8.json')

                                                            lojas
lojas_nordeste  [{'id_loja': 9, 'nome_loja': 'Loja Iota', 'cid...
lojas_norte     [{'id_loja': 11, 'nome_loja': 'Loja Lambda', '...

In [30]:
with open('arquivos/questao_8.json', 'r', encoding='utf-8') as f:
    df_8 = json.load(f)

In [31]:
df_8

{'lojas': {'lojas_nordeste': [{'id_loja': 9,
    'nome_loja': 'Loja Iota',
    'cidade': 'Recife',
    'estado': 'PE',
    'categoria': 'Acessórios',
    'vendas_mensais': 95,
    'faturamento_mensal': 28500.0},
   {'id_loja': 10,
    'nome_loja': 'Loja Kappa',
    'cidade': 'Fortaleza',
    'estado': 'CE',
    'categoria': 'Livros',
    'vendas_mensais': 180,
    'faturamento_mensal': 54000.0}],
  'lojas_norte': [{'id_loja': 11,
    'nome_loja': 'Loja Lambda',
    'cidade': 'Manaus',
    'estado': 'AM',
    'categoria': 'Eletrônicos',
    'vendas_mensais': 220,
    'faturamento_mensal': 110000.0},
   {'id_loja': 12,
    'nome_loja': 'Loja Mu',
    'cidade': 'Belém',
    'estado': 'PA',
    'categoria': 'Roupas',
    'vendas_mensais': 160,
    'faturamento_mensal': 48000.0}]}}

In [32]:
df_8_norte = pd.json_normalize(df_8, record_path=['lojas', 'lojas_norte'])
df_8_nordeste = pd.json_normalize(data=df_8, record_path=['lojas', 'lojas_nordeste'])

In [33]:
df_8 = pd.concat([df_8_nordeste, df_8_norte], ignore_index=True)

In [34]:
df_8

,id_loja,nome_loja,cidade,estado,categoria,vendas_mensais,faturamento_mensal
0,9,Loja Iota,Recife,PE,Acessórios,95,28500.0
1,10,Loja Kappa,Fortaleza,CE,Livros,180,54000.0
2,11,Loja Lambda,Manaus,AM,Eletrônicos,220,110000.0
3,12,Loja Mu,Belém,PA,Roupas,160,48000.0

<p>Após aplicar a normalização em uma lista presente no banco de dados, Diego percebeu que algumas colunas estavam ausentes no DataFrame resultante, embora estivessem nos dados originais. Ele sabe que o conjunto de dados deveria conter as seguintes colunas:

['cidade', 'estado', 'categoria', 'vendas_mensais', 'faturamento_mensal', 'id_loja', 'nome_loja']

No entanto, após aplicar a função json_normalize, as colunas 'id_loja' e 'nome_loja' não foram incluídas no DataFrame.</p>

In [35]:
with open('arquivos/questao_9.json', 'r', encoding='utf-8') as f:
    df_9 = json.load(f)

In [44]:
df_9

[{'id_loja': 13,
  'nome_loja': 'Loja Nu',
  'vendas': [{'cidade': 'Natal',
    'estado': 'RN',
    'categoria': 'Calçados',
    'vendas_mensais': 140,
    'faturamento_mensal': 42000.0}]},
 {'id_loja': 14,
  'nome_loja': 'Loja Xi',
  'vendas': [{'cidade': 'Goiânia',
    'estado': 'GO',
    'categoria': 'Acessórios',
    'vendas_mensais': 75,
    'faturamento_mensal': 22500.0}]},
 {'id_loja': 15,
  'nome_loja': 'Loja Omicron',
  'vendas': [{'cidade': 'São Luís',
    'estado': 'MA',
    'categoria': 'Livros',
    'vendas_mensais': 210,
    'faturamento_mensal': 63000.0}]},
 {'id_loja': 16,
  'nome_loja': 'Loja Pi',
  'vendas': [{'cidade': 'Maceió',
    'estado': 'AL',
    'categoria': 'Eletrônicos',
    'vendas_mensais': 50,
    'faturamento_mensal': 25000.0}]}]

In [45]:
pd.json_normalize(df_9)

   id_loja     nome_loja                                             vendas
0       13       Loja Nu  [{'cidade': 'Natal', 'estado': 'RN', 'categori...
1       14       Loja Xi  [{'cidade': 'Goiânia', 'estado': 'GO', 'catego...
2       15  Loja Omicron  [{'cidade': 'São Luís', 'estado': 'MA', 'categ...
3       16       Loja Pi  [{'cidade': 'Maceió', 'estado': 'AL', 'categor...

In [48]:
pd.json_normalize(df_9, meta=['id_loja', 'nome_loja'], record_path=['vendas'])

,cidade,estado,categoria,vendas_mensais,faturamento_mensal,id_loja,nome_loja
0,Natal,RN,Calçados,140,42000.0,13,Loja Nu
1,Goiânia,GO,Acessórios,75,22500.0,14,Loja Xi
2,São Luís,MA,Livros,210,63000.0,15,Loja Omicron
3,Maceió,AL,Eletrônicos,50,25000.0,16,Loja Pi

Exercício bonus

In [80]:
dados = [
    {
        "id_loja": 17,
        "nome_loja": "Loja Rho",
        "detalhes": [
            {"cidade": "João Pessoa", "estado": "PB"}
        ],
        "vendas": [
            {"categoria": "Roupas", "vendas_mensais": 125, "faturamento_mensal": 37500.0}
        ]
    },
    {
        "id_loja": 18,
        "nome_loja": "Loja Sigma",
        "detalhes": [
            {"cidade": "Vitória", "estado": "ES"}
        ],
        "vendas": [
            {"categoria": "Calçados", "vendas_mensais": 180, "faturamento_mensal": 54000.0}
        ]
    },
    {
        "id_loja": 19,
        "nome_loja": "Loja Tau",
        "detalhes": [
            {"cidade": "Aracaju", "estado": "SE"}
        ],
        "vendas": [
            {"categoria": "Acessórios", "vendas_mensais": 90, "faturamento_mensal": 27000.0}
        ]
    },
    {
        "id_loja": 20,
        "nome_loja": "Loja Upsilon",
        "detalhes": [
            {"cidade": "Teresina", "estado": "PI"}
        ],
        "vendas": [
            {"categoria": "Livros", "vendas_mensais": 240, "faturamento_mensal": 72000.0}
        ]
    }
]

In [84]:
df_detalhes = pd.json_normalize(dados, record_path='detalhes', meta=['id_loja', 'nome_loja'])
df_vendas = pd.json_normalize(dados, record_path='vendas', meta=['id_loja', 'nome_loja'])

In [85]:
df_final = pd.merge(df_detalhes, df_vendas, on=['id_loja', 'nome_loja'])

In [86]:
df_final

,cidade,estado,id_loja,nome_loja,categoria,vendas_mensais,faturamento_mensal
0,João Pessoa,PB,17,Loja Rho,Roupas,125,37500.0
1,Vitória,ES,18,Loja Sigma,Calçados,180,54000.0
2,Aracaju,SE,19,Loja Tau,Acessórios,90,27000.0
3,Teresina,PI,20,Loja Upsilon,Livros,240,72000.0