<h3>Exercicios aula 1</h3>

In [1]:
import pandas as pd

In [7]:
path = 'dados_sus.csv'

df = pd.read_csv(path, encoding='ISO-8859-1', sep=';', skiprows=3, skipfooter = 9, engine='python')

In [9]:
df.head()

,Unidade da Federação,2008/Jan,2008/Fev,2008/Mar,2008/Abr,2008/Mai,2008/Jun,2008/Jul,2008/Ago,2008/Set,...,2020/Jul,2020/Ago,2020/Set,2020/Out,2020/Nov,2020/Dez,2021/Jan,2021/Fev,2021/Mar,Total
0,Rondônia,"1388528,39","2931283,42","1541682,52","1525314,96","1645953,84","1406150,68","3065279,01","3231494,61","3117178,63",...,"11824687,13","11733307,76","10201985,14","7955139,45","9357946,29","8880836,55","9266014,59","7730597,04","11023309,47","996411254,68"
1,Acre,"902416,00","1497206,26","1794028,48","1730469,42","1819443,92","1828496,00","2511754,59","2089107,14","2275708,53",...,"3915193,20","3640142,82","3391242,21","4044321,44","3276590,10","3696997,31","3715723,12","3538427,92","4077045,92","450048530,47"
2,Amazonas,"4735529,42","7118990,57","8196635,49","8259378,42","7831399,90","8477273,62","9368858,72","9352532,70","9363099,35",...,"19769460,14","18059931,43","17841015,63","16408315,10","19895617,91","17765167,69","21430289,17","25917134,55","22032176,22","1917247936,05"
3,Roraima,"657889,53","777939,31","718688,03","839994,39","862347,96","832440,66","996693,09","894271,18","910424,17",...,"3015488,30","2826486,18","2928043,91","3090313,73","3621031,05","3454460,94","3266928,47","3519773,73","3985530,08","328876965,09"
4,Pará,"18864744,11","19553758,20","21937342,70","20842829,69","23249952,88","23240687,56","24002223,56","23341218,03","25172261,32",...,"40804126,43","44385715,88","36820249,47","36965931,34","39004315,80","38015145,79","38354682,46","37688314,23","33276392,89","4705309002,29"

<h3>Exercicios aula 2</h3>

In [1]:
import pandas as pd

sheet_id = '1pvBoLyX8kP0TjtUbadVMGdTl4yzm6bHMThhPiqCVtpw'

In [7]:
url = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet'

In [10]:
df = pd.read_csv(url)

In [11]:
df.to_csv('dados_emissoes_co2.csv',index=False, sep=';')

In [11]:
import json
import requests
import pandas as pd

In [6]:
dados_usuario = requests.get('https://jsonplaceholder.typicode.com/users')

In [7]:
resultado = json.loads(dados_usuario.text)

<h3>Normalizing</h3>

In [12]:
dados_usuarios_normalizados = pd.json_normalize(resultado, sep='_')

In [13]:
dados_usuarios_normalizados

,id,name,username,email,phone,website,address_street,address_suite,address_city,address_zipcode,address_geo_lat,address_geo_lng,company_name,company_catchPhrase,company_bs
0,1,Leanne Graham,Bret,Sincere@april.biz,1-770-736-8031 x56442,hildegard.org,Kulas Light,Apt. 556,Gwenborough,92998-3874,-37.3159,81.1496,Romaguera-Crona,Multi-layered client-server neural-net,harness real-time e-markets
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,010-692-6593 x09125,anastasia.net,Victor Plains,Suite 879,Wisokyburgh,90566-7771,-43.9509,-34.4618,Deckow-Crist,Proactive didactic contingency,synergize scalable supply-chains
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,1-463-123-4447,ramiro.info,Douglas Extension,Suite 847,McKenziehaven,59590-4157,-68.6102,-47.0653,Romaguera-Jacobson,Face to face bifurcated interface,e-enable strategic applications
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,493-170-9623 x156,kale.biz,Hoeger Mall,Apt. 692,South Elvis,53919-4257,29.4572,-164.2990,Robel-Corkery,Multi-tiered zero tolerance productivity,transition cutting-edge web services
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,(254)954-1289,demarco.info,Skiles Walks,Suite 351,Roscoeview,33263,-31.8129,62.5342,Keebler LLC,User-centric fault-tolerant solution,revolutionize end-to-end systems
5,6,Mrs. Dennis Schulist,Leopoldo_Corkery,Karley_Dach@jasper.info,1-477-935-8478 x6430,ola.org,Norberto Crossing,Apt. 950,South Christy,23505-1337,-71.4197,71.7478,Considine-Lockman,Synchronised bottom-line interface,e-enable innovative applications
6,7,Kurtis Weissnat,Elwyn.Skiles,Telly.Hoeger@billy.biz,210.067.6132,elvis.io,Rex Trail,Suite 280,Howemouth,58804-1099,24.8918,21.8984,Johns Group,Configurable multimedia task-force,generate enterprise e-tailers
7,8,Nicholas Runolfsdottir V,Maxime_Nienow,Sherwood@rosamond.me,586.493.6943 x140,jacynthe.com,Ellsworth Summit,Suite 729,Aliyaview,45169,-14.3990,-120.7677,Abernathy Group,Implemented secondary concept,e-enable extensible e-tailers
8,9,Glenna Reichert,Delphine,Chaim_McDermott@dana.io,(775)976-6794 x41206,conrad.com,Dayna Park,Suite 449,Bartholomebury,76495-3109,24.6463,-168.8889,Yost and Sons,Switchable contextually-based project,aggregate real-time technologies
9,10,Clementina DuBuque,Moriah.Stanton,Rey.Padberg@karina.biz,024-648-3804,ambrose.net,Kattie Turnpike,Suite 198,Lebsackbury,31428-2261,-38.2386,57.2232,Hoeger LLC,Centralized empowering task-force,target end-to-end models

In [14]:
dados_usuarios_normalizados.to_csv('dados_usuarios_normalizados.csv', sep=',')


<h3>Atividades Aula 4</h3>

In [2]:
import pandas as pd

In [8]:
path= 'lista_de_paises.html'.encode('utf-8')

In [17]:
paises_df = pd.read_html(path)

In [14]:
paises_df

[     Unnamed: 0 Posição                    País (ou território dependente)  \
 0           NaN       1                                              Índia
 1           NaN       2                                      China[nota 1]
 2           NaN       3                                     Estados Unidos
 3           NaN       4                                          Indonésia
 4           NaN       5                                          Paquistão
 ..          ...     ...                                                ...
 245         NaN       –                     Ilha de Ascensão (Reino Unido)
 246         NaN     195                                           Vaticano
 247         NaN       –  [[File:|22x20px|border |alt=|link=]] Ilhas Coc...
 248         NaN       –                     Tristão da Cunha (Reino Unido)
 249         NaN       –                       Ilhas Pitcairn (Reino Unido)

     Estimativa da ONU Mudança desde a última estimativa  \
 0       1 417 492 000                       -12 692 000
 1       1 407 934 000                        -1 390 000
 2         342 181 000                        -2 084 000
 3         285 783 000                        +3 337 000
 4         256 204 000                        +6 567 000
 ..                ...                               ...
 245             1 100                               NaN
 246               879                               NaN
 247               605                               NaN
 248               264                               NaN
 249                67                               NaN

          Estimativa Oficial
 0        Estimativa oficial
 1             Censo oficial
 2             Censo oficial
 3        Estimativa oficial
 4        Estimativa oficial
 ..                      ...
 245  Estimativa oficial[10]
 246      Estimativa oficial
 247      Estimativa oficial
 248  Estimativa oficial[11]
 249      Estimativa oficial

 [250 rows x 6 columns],
    vdeListas de países                              vdeListas de países.1
 0             Ambiente  Bem-estar sustentável Desempenho ambiental Emi...
 1              Códigos  COI FIFA FIPS ISO Prefixo naval Telefônicos TL...
 2           Demografia  Esperança de vida Fecundidade Imigrantes Morta...
 3             Economia  Capacidade Nacional Capital Humano Competitivi...
 4              Consumo  Bebidas Cerveja Idade legal Cannabis Adultos C...
 5              Energia  Eletricidade Produção Renovável Gás natural Ex...
 6                  PIB  Crescimento Real PIB Nominal per capita PIB po...
 7             Produção  Alumínio Antimônio Bauxita Bismuto Carvão Rese...
 8           Transporte  Aeroportos Automóveis per capita Produzidos He...
 9            Geografia  Área Capital Continente Fronteiras Terrestres ...
 10         Militarismo  Armas de fogo Artilharia Batalhas Blindados de...
 11              Órgãos  BRICS Commonwealth COI CPLP Estatuto de Roma F...
 12            Política  Chefes de Estado e de Governo Constituições Co...
 13               Saúde  Antidepressivos HIV/AIDS em adultos Obesidade ...
 14            Símbolos  Emblemas Etimologia Gentílicos Grafias múltipl...
 15           Sociedade  Aborto Arranha-céus e estruturas Data de funda...,
             0                                                  1
 0     Consumo  Bebidas Cerveja Idade legal Cannabis Adultos C...
 1     Energia  Eletricidade Produção Renovável Gás natural Ex...
 2         PIB  Crescimento Real PIB Nominal per capita PIB po...
 3    Produção  Alumínio Antimônio Bauxita Bismuto Carvão Rese...
 4  Transporte  Aeroportos Automóveis per capita Produzidos He...]

In [15]:
paises_df[0]

,Unnamed: 0,Posição,País (ou território dependente),Estimativa da ONU,Mudança desde a última estimativa,Estimativa Oficial
0,NaN,1,Índia,1 417 492 000,-12 692 000,Estimativa oficial
1,NaN,2,China[nota 1],1 407 934 000,-1 390 000,Censo oficial
2,NaN,3,Estados Unidos,342 181 000,-2 084 000,Censo oficial
3,NaN,4,Indonésia,285 783 000,+3 337 000,Estimativa oficial
4,NaN,5,Paquistão,256 204 000,+6 567 000,Estimativa oficial
...,...,...,...,...,...,...
245,NaN,–,Ilha de Ascensão (Reino Unido),1 100,NaN,Estimativa oficial[10]
246,NaN,195,Vaticano,879,NaN,Estimativa oficial
247,NaN,–,[[File:|22x20px|border |alt=|link=]] Ilhas Coc...,605,NaN,Estimativa oficial
248,NaN,–,Tristão da Cunha (Reino Unido),264,NaN,Estimativa oficial[11]
249,NaN,–,Ilhas Pitcairn (Reino Unido),67,NaN,Estimativa oficial

<h3>Atividades aula 5</h3>

In [14]:
import pandas as pd
from sqlalchemy import create_engine, inspect, MetaData, Table, text

In [3]:
engine = create_engine('sqlite:///:memory:')
url = 'https://raw.githubusercontent.com/alura-cursos/Pandas/main/clientes_banco.csv'

In [4]:
clientes_csv = pd.read_csv(url)

In [8]:
clientes_csv.to_sql('clientes2', engine, index=False)

438463

In [10]:
pd.read_sql_table('clientes2', engine).head()

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,5008804,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
1,5008805,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
2,5008806,58,Ensino médio,Casado,2,Empregado,Segurança,3,112500.0,1,Casa/apartamento próprio
3,5008808,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
4,5008809,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio

In [16]:
query = 'UPDATE clientes2 SET Rendimento_anual=300000 WHERE ID_Cliente=6840104'
with engine.connect() as conn:
    result = conn.execute(text(query))
    conn.commit()

In [18]:
query = 'SELECT * FROM clientes2 WHERE ID_Cliente=6840104'
filtro_especifico = pd.read_sql(query, engine)
filtro_especifico

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,6840104,62,Ensino médio,Divorciado,1,Pensionista,Outro,0,300000.0,0,Casa/apartamento próprio

In [21]:
query = 'SELECT * FROM clientes2 WHERE ID_Cliente=5008809'
pd.read_sql(query, engine)

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,5008809,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio

In [22]:
query = 'DELETE FROM clientes2 WHERE ID_Cliente=5008809'
with engine.connect() as conn:
    result = conn.execute(text(query))
    conn.commit()

In [23]:
query = 'SELECT * FROM clientes2 WHERE ID_Cliente=5008809'
pd.read_sql(query, engine)

Empty DataFrame
Columns: [ID_Cliente, Idade, Grau_escolaridade, Estado_civil, Tamanho_familia, Categoria_de_renda, Ocupacao, Anos_empregado, Rendimento_anual, Tem_carro, Moradia]
Index: []

In [30]:
query = 'INSERT INTO clientes2 (ID_Cliente, Idade, Grau_escolaridade, Estado_civil, ' \
        'Tamanho_familia, Categoria_de_renda, Ocupacao, Anos_empregado, ' \
        'Rendimento_anual, Tem_carro, Moradia) ' \
        'VALUES (6850985, 33, "Doutorado", "Solteiro", 1, "Empregado", "TI", ' \
        '2, 290000, 0, "Casa/apartamento próprio")'

with engine.connect() as conn:
    result = conn.execute(text(query))
    conn.commit()

In [31]:
query = 'SELECT * FROM clientes2 WHERE ID_Cliente=6850985'
pd.read_sql(query, engine)

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,6850985,33,Doutorado,Solteiro,1,Empregado,TI,2,290000.0,0,Casa/apartamento próprio